/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_nsu_g_beryanov_CPUInfo */

#ifndef _Included_ru_nsu_g_beryanov_CPUInfo
#define _Included_ru_nsu_g_beryanov_CPUInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_nsu_g_beryanov_CPUInfo
 * Method:    show
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_nsu_g_beryanov_CPUInfo_show
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
